spring: 
  profiles:
    active:
    - dev  
--- 
server: 
  port: 8201
spring: 
  profiles: dev 
  application: 
    name: cloud-config-dev
---
server: 
  port: 8202
spring: 
  profiles: test
  application: 
    name: cloud-config-test    